feedbin/config/routes.rb
require 'sidekiq/web'

Feedbin::Application.routes.draw do

  root to: 'site#index'

  mount Sidekiq::Web, at: '/sidekiq'
  mount StripeEvent::Engine, at: '/stripe'

  get :health_check, to: proc {|env| [200, {}, ["OK"]] }

  get :home, to: 'site#home'
  get :apps, to: 'site#apps'

  get :manifest, to: 'site#manifest'

  post '/emails' => 'emails#create'

  match '/404', to: 'errors#not_found', via: :all
  get '/starred/:starred_token', to: 'starred#index', as: 'starred'

  get    :signup,         to: 'users#new',           as: 'signup'
  get    :login,          to: 'sessions#new',        as: 'login'
  get    :privacy_policy, to: 'site#privacy_policy', as: 'privacy_policy'
  delete :logout,         to: 'sessions#destroy',    as: 'logout'

  post 'apple_push_notifications/:version/pushPackages/:website_push_id', as: :apple_push_notifications_package, to: 'apple_push_notifications#create', website_push_id: /.*/

  post 'apple_push_notifications/:version/devices/:device_token/registrations/:website_push_id', as: :apple_push_notifications_update, to: 'apple_push_notifications#update', website_push_id: /.*/

  delete 'apple_push_notifications/:version/devices/:device_token/registrations/:website_push_id', as: :apple_push_notifications_delete, to: 'apple_push_notifications#delete', website_push_id: /.*/

  post 'apple_push_notifications/:version/log', as: :apple_push_notifications_log, to: 'apple_push_notifications#log'

  resources :tags,           only: [:index, :show, :update, :destroy]
  resources :billing_events, only: [:show]
  resources :imports
  resources :sessions
  resources :password_resets
  resources :sharing_services, path: 'settings/sharing', only: [:index]
  resources :actions, path: 'settings/actions', only: [:index]
  resources :saved_searches

  resources :subscriptions,  only: [:index, :create, :destroy] do
    collection do
      patch :update_multiple
    end
  end

  resources :users, id: /.*/ do
    member do
      patch :settings_update, controller: :settings
      patch :view_settings_update, controller: :settings
      patch :sharing_services_update, controller: :sharing_services
      patch :actions_update, controller: :actions
    end
  end

  resources :feeds, only: [:index, :edit, :create, :update] do
    resources :entries, only: [:index], controller: :feeds_entries
    collection do
      get :view_unread
      get :view_all
      get :auto_update
    end
  end

  resources :entries, only: [:show, :index] do
    member do
      post :content
      post :unread_entries, to: 'unread_entries#update'
      post :starred_entries, to: 'starred_entries#update'
      post :mark_as_read, to: 'entries#mark_as_read'
      get :push_view
    end
    collection do
      get :starred
      get :unread
      get :preload
      get :search
      post :mark_all_as_read
      post :mark_direction_as_read
    end
  end

  get :settings, to: 'settings#settings'
  namespace :settings do
    get :account
    get :billing
    get :import_export
    get :feeds
    get :help
    post :update_credit_card
    post :mark_favicon_complete
    post :update_plan
    post :font
    post :font_increase
    post :font_decrease
    post :entry_width
  end

  constraints subdomain: 'api' do
    namespace :api, path: nil do
      namespace :v1 do
        match '*path', to: 'api#gone', via: :all
      end
    end
  end

  constraints subdomain: 'api' do
    namespace :api, path: nil do
      namespace :v2 do
        resources :feeds, only: [:show] do
          resources :entries, only: [:index, :show], controller: :feeds_entries
        end
        resources :subscriptions,  only: [:index, :show, :create, :destroy, :update]
        post "subscriptions/:id/update", to: 'subscriptions#update'

        resources :taggings,       only: [:index, :show, :create, :destroy]
        resources :entries,        only: [:index, :show]

        resources :unread_entries, only: [:index, :show, :create]
        delete 'unread_entries', to: 'unread_entries#destroy'
        post 'unread_entries/delete', to: 'unread_entries#destroy'

        resources :starred_entries, only: [:index, :show, :create]
        delete 'starred_entries', to: 'starred_entries#destroy'
        post 'starred_entries/delete', to: 'starred_entries#destroy'

        resources :saved_searches,  only: [:index, :show, :create, :destroy, :update]
        post "saved_searches/:id/update", to: 'saved_searches#update'
      end
    end
  end

end

feedbin/app/models/saved_search.rb
class SavedSearch < ActiveRecord::Base
  belongs_to :user
end

feedbin/app/controllers/api/v2/saved_searches_controller.rb
module Api
  module V2
    class SavedSearchesController < ApiController

      respond_to :json

      before_action :validate_content_type, only: [:create]
      before_action :validate_create, only: [:create]

      def index
        @user = current_user
        @saved_searches = @user.saved_searches.order("lower(name)")
        if @saved_searches.any?
          fresh_when(etag: @saved_searches, last_modified: @saved_searches.maximum(:updated_at))
        else
          @saved_searches = []
        end
      end

      def show
        @user = current_user
        saved_search = @user.saved_searches.where(id: params[:id]).first

        if saved_search.present?
          params[:query] = saved_search.query
          if params[:include_entries] && params[:include_entries] == "true"
            @entries = Entry.search(params, @user)
            links_header(@entries, 'api_v2_saved_search_url', saved_search.id)
          else
            params[:load] = false
            entries = Entry.search(params, @user)
            links_header(entries, 'api_v2_saved_search_url', saved_search.id)
            render json: entries.results.map {|entry| entry.id.to_i}.to_json
          end
        else
          status_forbidden
        end

      end

      def create
        @user = current_user
        @saved_search = @user.saved_searches.create(saved_search_params)
        render status: :created, location: api_v2_saved_search_url(@saved_search, format: :json)
      end

      def destroy
        @user = current_user
        @saved_search = @user.saved_searches.where(id: params[:id]).first
        if @saved_search.present?
          @saved_search.destroy
          render nothing: true, status: :no_content
        else
          status_forbidden
        end
      end

      def update
        @user = current_user
        @saved_search = @user.saved_searches.where(id: params[:id]).first
        if @saved_search.present?
          @saved_search.update(saved_search_params)
        else
          status_forbidden
        end
      end

      private

      def saved_search_params
        params.require(:saved_search).permit(:query, :name)
      end

      def validate_create
        needs 'query', 'name'
      end

    end
  end
end

feedbin/app/controllers/saved_searches_controller.rb
class SavedSearchesController < ApplicationController

  def show
    @user = current_user
    @saved_search = SavedSearch.where(user: @user, id: params[:id]).take!

    update_selected_feed!("saved_search", params[:id])

    params[:query] = @saved_search.query

    @entries = Entry.search(params, @user)
    @entries = update_with_state(@entries)
    @page_query = @entries

    @append = !params[:page].nil?

    @type = 'saved_search'
    @data = nil

    @collection_title = @saved_search.name
    @collection_favicon = 'favicon-search'

    respond_to do |format|
      format.js { render partial: 'shared/entries' }
    end
  end

  def create
    @user = current_user
    @saved_search = @user.saved_searches.create(saved_search_params)
    get_feeds_list
  end

  def edit
    @user = current_user
    @saved_search = SavedSearch.where(user: @user, id: params[:id]).take!
  end

  def update
    @user = current_user
    @saved_search = SavedSearch.where(user: @user, id: params[:id]).take!
    @saved_search.update(saved_search_params)
    get_feeds_list
  end

  def destroy
    @user = current_user
    @saved_search = SavedSearch.where(user: @user, id: params[:id]).take!
    @saved_search.destroy
    get_feeds_list
  end

  private

  def saved_search_params
    params.require(:saved_search).permit(:query, :name)
  end

end

feedbin/app/views/saved_searches/_form.html.erb
<%= form_for(saved_search, remote: true) do |f| %>
  <%= f.hidden_field :query %>
  <%= f.text_field :name, placeholder: 'Name' %>
  <%= f.submit class: 'button button-text' %>
<% end %>

feedbin/app/views/saved_searches/_saved_search.html.erb
<% present saved_search do |saved_search_presenter| %>
  <li data-saved-search-id="<%= saved_search.id %>" data-feed-id="saved-search-<%= saved_search.id %>" class="<%= selected("saved_search_#{saved_search.id}") %>">
    <%= link_to saved_search_path(saved_search.id), remote: true, class: 'feed-link saved-search-link', data: { behavior: 'selectable reset_entry_position show_entries open_item feed_link', mark_read: {type: 'saved_search', data: saved_search.id, message: "Mark #{saved_search.name} as read?"}.to_json } do %>
      <span class="favicon-wrap">
        <span class="favicon favicon-search"></span>
      </span>
      <%= saved_search_presenter.name %>
      <%= link_to "edit", edit_saved_search_path(saved_search.id), remote: true, class: 'feed-action-button' %>
    <% end %>
  </li>
<% end %>

feedbin/app/views/saved_searches/create.js.erb
feedbin.updateFeeds('<%= j render partial: 'feeds/feeds', locals: {collections: @collections, saved_searches: @saved_searches, tags: @tags, feeds: @feeds} %>');
$('.saved-search-wrap').removeClass('show');
$('[data-behavior~=save_search_link]').attr('disabled', 'disabled');
$('#query').val('');
$("[data-saved-search-id=<%= @saved_search.id %>] a.feed-link").click();

feedbin/app/views/saved_searches/destroy.js.erb
feedbin.updateFeeds('<%= j render partial: 'feeds/feeds', locals: {collections: @collections, saved_searches: @saved_searches, tags: @tags, feeds: @feeds} %>');
feedbin.updateEntries('');
feedbin.updateEntryContent('');
feedbin.hideTagsForm();
$('.app').addClass('nothing-selected').removeClass('feed-selected entry-selected')
$('[data-behavior~=show_tags_form]').replaceWith('<%= j render partial: "shared/buttons/tag", locals: {feed: nil, tags: nil, tag: nil} %>');
$('[data-behavior~=unsubscribe]').replaceWith('<%= j render partial: "shared/buttons/destroy_tag", locals: {tag: nil} %>');
feedbin.disableMarkRead()

feedbin/app/views/saved_searches/edit.js.erb
$('[data-behavior~=saved_search_form_target]').html('<%= j render partial: "saved_searches/form", locals: {saved_search: @saved_search} %>');
$('.saved-search-wrap').addClass('show');
$('#query').val('<%= @saved_search.query.html_safe %>')

feedbin/app/views/saved_searches/update.js.erb
feedbin.updateFeeds('<%= j render partial: 'feeds/feeds', locals: {collections: @collections, saved_searches: @saved_searches, tags: @tags, feeds: @feeds} %>');
$('.saved-search-wrap').removeClass('show');
$('#query').val('');
$("[data-saved-search-id=<%= @saved_search.id %>] a.feed-link").click();