feedbin/config/routes.rb
require 'sidekiq/web'

Feedbin::Application.routes.draw do

  root to: 'site#index'

  mount Sidekiq::Web, at: '/sidekiq'
  mount StripeEvent::Engine, at: '/stripe'

  get :health_check, to: proc {|env| [200, {}, ["OK"]] }

  get :home, to: 'site#home'
  get :apps, to: 'site#apps'

  get :manifest, to: 'site#manifest'

  post '/emails' => 'emails#create'

  match '/404', to: 'errors#not_found', via: :all
  get '/starred/:starred_token', to: 'starred#index', as: 'starred'

  get    :signup,         to: 'users#new',           as: 'signup'
  get    :login,          to: 'sessions#new',        as: 'login'
  get    :privacy_policy, to: 'site#privacy_policy', as: 'privacy_policy'
  delete :logout,         to: 'sessions#destroy',    as: 'logout'

  post 'apple_push_notifications/:version/pushPackages/:website_push_id', as: :apple_push_notifications_package, to: 'apple_push_notifications#create', website_push_id: /.*/

  post 'apple_push_notifications/:version/devices/:device_token/registrations/:website_push_id', as: :apple_push_notifications_update, to: 'apple_push_notifications#update', website_push_id: /.*/

  delete 'apple_push_notifications/:version/devices/:device_token/registrations/:website_push_id', as: :apple_push_notifications_delete, to: 'apple_push_notifications#delete', website_push_id: /.*/

  post 'apple_push_notifications/:version/log', as: :apple_push_notifications_log, to: 'apple_push_notifications#log'

  resources :tags,           only: [:index, :show, :update, :destroy]
  resources :billing_events, only: [:show]
  resources :imports
  resources :sessions
  resources :password_resets
  resources :sharing_services, path: 'settings/sharing', only: [:index]
  resources :actions, path: 'settings/actions', only: [:index]
  resources :saved_searches

  resources :subscriptions,  only: [:index, :create, :destroy] do
    collection do
      patch :update_multiple
    end
  end

  resources :users, id: /.*/ do
    member do
      patch :settings_update, controller: :settings
      patch :view_settings_update, controller: :settings
      patch :sharing_services_update, controller: :sharing_services
      patch :actions_update, controller: :actions
    end
  end

  resources :feeds, only: [:index, :edit, :create, :update] do
    resources :entries, only: [:index], controller: :feeds_entries
    collection do
      get :view_unread
      get :view_all
      get :auto_update
    end
  end

  resources :entries, only: [:show, :index] do
    member do
      post :content
      post :unread_entries, to: 'unread_entries#update'
      post :starred_entries, to: 'starred_entries#update'
      post :mark_as_read, to: 'entries#mark_as_read'
      get :push_view
    end
    collection do
      get :starred
      get :unread
      get :preload
      get :search
      post :mark_all_as_read
      post :mark_direction_as_read
    end
  end

  get :settings, to: 'settings#settings'
  namespace :settings do
    get :account
    get :billing
    get :import_export
    get :feeds
    get :help
    post :update_credit_card
    post :mark_favicon_complete
    post :update_plan
    post :font
    post :font_increase
    post :font_decrease
    post :entry_width
  end

  constraints subdomain: 'api' do
    namespace :api, path: nil do
      namespace :v1 do
        match '*path', to: 'api#gone', via: :all
      end
    end
  end

  constraints subdomain: 'api' do
    namespace :api, path: nil do
      namespace :v2 do
        resources :feeds, only: [:show] do
          resources :entries, only: [:index, :show], controller: :feeds_entries
        end
        resources :subscriptions,  only: [:index, :show, :create, :destroy, :update]
        post "subscriptions/:id/update", to: 'subscriptions#update'

        resources :taggings,       only: [:index, :show, :create, :destroy]
        resources :entries,        only: [:index, :show]

        resources :unread_entries, only: [:index, :show, :create]
        delete 'unread_entries', to: 'unread_entries#destroy'
        post 'unread_entries/delete', to: 'unread_entries#destroy'

        resources :starred_entries, only: [:index, :show, :create]
        delete 'starred_entries', to: 'starred_entries#destroy'
        post 'starred_entries/delete', to: 'starred_entries#destroy'

        resources :saved_searches,  only: [:index, :show, :create, :destroy, :update]
        post "saved_searches/:id/update", to: 'saved_searches#update'
      end
    end
  end

end

feedbin/app/views/shared/_analytics_event.html.erb
ga('send', <%= {hitType: 'event'}.merge(@analytics_event).to_json.html_safe %>);

feedbin/app/views/shared/_credit_card_form.html.erb
<p>
  <%= text_field_tag :card_number, nil, name: nil, placeholder: "Credit Card Number" %>

  <%= text_field_tag :card_code, nil, name: nil, placeholder: "Card Security Code (CVC)" %>

  <%= label_tag :card_month, "Card Expiration" %>
  <%= select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month"} %>
  <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year + 10}, {name: nil, id: "card_year"} %>
</p>

feedbin/app/views/shared/_data.html.erb
<%=
content_tag :div, '',
  data: {
    login_url: login_url,
    favicon_complete: false,
    mark_favicon_complete_path: settings_mark_favicon_complete_path,
    tags_path: tags_path(format: :json),
    mobile: mobile,
    user_titles: @user_titles.to_json,
    preload_entries_path: preload_entries_path(format: :json),
    sticky_readability: (@user.sticky_view_inline == '1'),
    readability_settings: @readability_settings.to_json,
    show_unread_count:  (@user.show_unread_count == '1'),
    precache_images: (@user.precache_images == '1'),
    auto_update_path: auto_update_feeds_path,
    font_sizes: Feedbin::Application.config.font_sizes.to_json,
    mark_as_read_path: mark_all_as_read_entries_path,
    mark_as_read_confirmation: (@user.mark_as_read_confirmation == '1'),
    mark_direction_as_read_entries: mark_direction_as_read_entries_path
  },
  class: 'hide',
  id: 'feedbin-data'
%>

feedbin/app/views/shared/_entries.js.erb
var entries = '<%= j render partial: "entries/entry", collection: @entries %>';
var header = '<%= j render partial: "entries/entries_header", locals: {feed: @feed || nil} %>';

<% if @append %>
	feedbin.appendEntries(entries, header);
<% else %>
	feedbin.updateEntries(entries, header);
<% end %>

feedbin.localizeTime($('[data-behavior~=entries_target]'))

feedbin.applyUserTitles()

$('[data-behavior~=show_tags_form]').replaceWith('<%= j render partial: "shared/buttons/tag", locals: {feed: @feed || nil, tags: @tags, tag: @tag || nil} %>');

<% if @type && @type == 'tag' %>
  $('[data-behavior~=unsubscribe]').replaceWith('<%= j render partial: "shared/buttons/destroy_tag", locals: {tag: @tag} %>');
<% elsif @type && @type == 'saved_search' %>
  $('[data-behavior~=unsubscribe]').replaceWith('<%= j render partial: "shared/buttons/destroy_saved_search", locals: {saved_search: @saved_search} %>');
<% else %>
  $('[data-behavior~=unsubscribe]').replaceWith('<%= j render partial: "shared/buttons/unsubscribe", locals: {feed: @feed || nil} %>');
<% end %>

feedbin.updatePager('<%= j will_paginate(@page_query) %>');

feedbin.data.viewMode = "<%= j session[:view_mode] %>";

feedbin.preloadEntries(<%= @entries.map{ |entry| entry.id }.to_json.html_safe %>);

<% if @search %>
feedbin.markReadData = {type: "search", data: "<%= @escaped_query %>", message: "Mark search for <%= @escaped_query %> as read?"}
$('.saved-search-wrap').removeClass('show')
$('.app').addClass('feed-selected').removeClass('nothing-selected entry-selected');
$('[data-behavior~=save_search_link]').removeAttr('disabled');
$('[data-behavior~=saved_search_form_target]').html('<%= j render partial: "saved_searches/form", locals: {saved_search: @saved_search} %>');
<% end %>

feedbin/app/views/shared/_entry_settings.html.erb
<div class="entry-settings">
  <div class="setting-wrap">
    <%= form_tag settings_font_path, remote: true do %>
      <%= select_tag "font", options_for_select(Feedbin::Application.config.fonts, @user.font || 'default'), data: {behavior: 'change_font'} %>
    <% end %>
  </div>
  <div class="setting-wrap">
    <%= link_to "", settings_font_decrease_path, remote: true, method: :post, class: 'button-decrease-font', data: {behavior: 'decrease_font'} %>
  </div>
  <div class="setting-wrap">
    <%= link_to "", settings_font_increase_path, remote: true, method: :post, class: 'button-increase-font', data: {behavior: 'increase_font'} %>
  </div>
  <div class="setting-wrap">
    <%= link_to "", settings_entry_width_path, remote: true, method: :post, class: 'button-entry-width', data: {behavior: 'entry_width'} %>
  </div>
</div>

feedbin/app/views/shared/_entry_settings_button.html.erb
<div class="entry-button-wrap">
  <button class="entry-button button-settings" title="Entry Settings">
    <%= render partial: "shared/svg/settings" %>
  </button>
</div>

feedbin/app/views/shared/_feeds_toolbar.erb
<div class="feeds-toolbar">
  <table cellpadding="0">
    <tbody>
      <tr>
        <td>
          <%= render partial: 'shared/buttons/tag', locals: {feed: nil, tags: nil, tag: nil} %>
        </td>
        <td>
          <%= render partial: 'shared/buttons/mark_all_as_read', locals: {type: nil, data: nil} %>
        </td>
        <td>
          <%= render partial: 'shared/buttons/unsubscribe', locals: {feed: nil} %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

feedbin/app/views/shared/_flash.html.erb
<% if flash[:alert] %>
<div class="alert alert-info">
  <%= flash[:alert] %>
</div>
<% end %>

<% if flash[:error] %>
<div class="alert alert-error">
  <%= flash[:error] %>
</div>
<% end %>

<% if flash[:notice] %>
<div class="alert alert-success">
  <%= flash[:notice] %>
</div>
<% end %>

feedbin/app/views/shared/_keyboard_shortcuts.html.erb
<table class="table">
  <tr>
    <th>Action</th>
    <th>Key</th>
  </tr>
  <tr>
    <td>Navigate through feeds and entries</td>
    <td>
      <p><span class="key">↑</span> <span class="key">↓</span> <span class="key">←</span> <span class="key">→</span></p>
      <span class="key">j</span> <span class="key">k</span> <span class="key">h</span> <span class="key">l</span>
    </td>
  </tr>
  <tr>
    <td>Navigate through unread items</td>
    <td><span class="key wide">space</span></td>
  </tr>
  <tr>
    <td>Expand/collapse tag drawer</td>
    <td><span class="key">e</span></td>
  </tr>
  <tr>
    <td>Star entry</td>
    <td><span class="key">s</span></td>
  </tr>
  <tr>
    <td>Toggle read/unread</td>
    <td><span class="key">m</span></td>
  </tr>
  <tr>
    <td>Open original</td>
    <td><span class="key">v</span></td>
  </tr>
  <tr>
    <td>Open original in background (FireFox not supported)</td>
    <td><span class="key wide">shift</span> <span class="key">v</span></td>
  </tr>
  <tr>
    <td>View with Readability</td>
    <td><span class="key">c</span></td>
  </tr>
  <tr>
    <td>Refresh feeds list</td>
    <td><span class="key">r</span></td>
  </tr>
  <tr>
    <td>Open sharing menu</td>
    <td><span class="key">f</span></td>
  </tr>
  <tr>
    <td>Go to all</td>
    <td><span class="key">g</span> then <span class="key">a</span></td>
  </tr>
  <tr>
    <td>Go to starred</td>
    <td><span class="key">g</span> then <span class="key">s</span></td>
  </tr>
  <tr>
    <td>Mark all as read</td>
    <td><span class="key wide">shift</span> <span class="key">a</span></td>
  </tr>
  <tr>
    <td>Focus search field</td>
    <td><span class="key">/</span></td>
  </tr>
  <tr>
    <td>Focus subscription field</td>
    <td><span class="key">a</span></td>
  </tr>
  <tr>
    <td>Unfocus field</td>
    <td><span class="key wide">escape</span></td>
  </tr>
  <tr>
    <td>Show help</td>
    <td><span class="key">?</span></td>
  </tr>
</table>

feedbin/app/views/shared/_keyboard_shortcuts_wrap.html.erb
<div class="hide" data-behavior="keyboard_shortcuts">
  <div class="modal hide fade">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Feedbin Help</h3>
      </div>
      <div class="modal-body">
        <%= render partial: "shared/keyboard_shortcuts" %>
      </div>
      <div class="modal-footer">
        <div class="half text-left">
          <a href="/home">Home Page</a>
        </div>
        <div class="half">
          <a href="https://github.com/feedbin/support#readme">Contact & Support</a>
        </div>
      </div>
  </div>
</div>

feedbin/app/views/shared/_messages.html.erb
<% @messages.each do |message| %>
  <%= message.sanitize.html_safe %>.
<% end %>

feedbin/app/views/shared/_public_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <p><a href="http://blog.feedbin.me">Blog</a> | <a href="<%= apps_path %>">Apps</a> | <a href="https://github.com/feedbin/support#readme">Support</a> | <a href="https://github.com/feedbin/feedbin-api#readme">API</a> | <a href="<%= privacy_policy_path %>">Privacy Policy</a></p>
      </div>
      <div class="col-sm-6 text-right">
        <p><a href="mailto:support@feedbin.me">Email</a> | <a href="https://twitter.com/feedbin">Twitter</a> | <a href="https://github.com/feedbin/feedbin">GitHub</a></p>
      </div>
    </div>
    <hr class="space-small" />
    <p class="copy">© <%= Time.now.year %> Feedbin, Inc.</p>
  </div>
</footer>

feedbin/app/views/shared/_resizable_form.html.erb
<%= form_for @user, url: view_settings_update_user_path(@user), remote: 'true', html: { class: 'hide', data: {behavior: 'resizable_form'} } do |f| %>
  <%= hidden_field_tag 'column_widths', 'column_widths' %>
  <%= hidden_field_tag 'column', '' %>
  <%= hidden_field_tag 'width', '' %>
<% end %>

feedbin/app/views/shared/_update_view_mode.js.erb
feedbin.updateFeeds('<%= j render partial: 'feeds/feeds', locals: {collections: @collections, saved_searches: @saved_searches, tags: @tags, feeds: @feeds} %>');

$('[data-behavior~=view_all]').replaceWith('<%= j render partial: 'shared/buttons/view_all' %>');
$('[data-behavior~=view_unread]').replaceWith('<%= j render partial: 'shared/buttons/view_unread' %>');

feedbin.data.viewMode = "<%= @view_mode.to_s %>";
feedbin.updateTitle('<%= j @user.title_with_count %>');

<% if @clear_hide_queue %>
  feedbin.hideQueue = [];
<% end %>