feedbin/config/routes.rb
require 'sidekiq/web'

Feedbin::Application.routes.draw do

  root to: 'site#index'

  mount Sidekiq::Web, at: '/sidekiq'
  mount StripeEvent::Engine, at: '/stripe'

  get :health_check, to: proc {|env| [200, {}, ["OK"]] }

  get :home, to: 'site#home'
  get :apps, to: 'site#apps'

  get :manifest, to: 'site#manifest'

  post '/emails' => 'emails#create'

  match '/404', to: 'errors#not_found', via: :all
  get '/starred/:starred_token', to: 'starred#index', as: 'starred'

  get    :signup,         to: 'users#new',           as: 'signup'
  get    :login,          to: 'sessions#new',        as: 'login'
  get    :privacy_policy, to: 'site#privacy_policy', as: 'privacy_policy'
  delete :logout,         to: 'sessions#destroy',    as: 'logout'

  post 'apple_push_notifications/:version/pushPackages/:website_push_id', as: :apple_push_notifications_package, to: 'apple_push_notifications#create', website_push_id: /.*/

  post 'apple_push_notifications/:version/devices/:device_token/registrations/:website_push_id', as: :apple_push_notifications_update, to: 'apple_push_notifications#update', website_push_id: /.*/

  delete 'apple_push_notifications/:version/devices/:device_token/registrations/:website_push_id', as: :apple_push_notifications_delete, to: 'apple_push_notifications#delete', website_push_id: /.*/

  post 'apple_push_notifications/:version/log', as: :apple_push_notifications_log, to: 'apple_push_notifications#log'

  resources :tags,           only: [:index, :show, :update, :destroy]
  resources :billing_events, only: [:show]
  resources :imports
  resources :sessions
  resources :password_resets
  resources :sharing_services, path: 'settings/sharing', only: [:index]
  resources :actions, path: 'settings/actions', only: [:index]
  resources :saved_searches

  resources :subscriptions,  only: [:index, :create, :destroy] do
    collection do
      patch :update_multiple
    end
  end

  resources :users, id: /.*/ do
    member do
      patch :settings_update, controller: :settings
      patch :view_settings_update, controller: :settings
      patch :sharing_services_update, controller: :sharing_services
      patch :actions_update, controller: :actions
    end
  end

  resources :feeds, only: [:index, :edit, :create, :update] do
    resources :entries, only: [:index], controller: :feeds_entries
    collection do
      get :view_unread
      get :view_all
      get :auto_update
    end
  end

  resources :entries, only: [:show, :index] do
    member do
      post :content
      post :unread_entries, to: 'unread_entries#update'
      post :starred_entries, to: 'starred_entries#update'
      post :mark_as_read, to: 'entries#mark_as_read'
      get :push_view
    end
    collection do
      get :starred
      get :unread
      get :preload
      get :search
      post :mark_all_as_read
      post :mark_direction_as_read
    end
  end

  get :settings, to: 'settings#settings'
  namespace :settings do
    get :account
    get :billing
    get :import_export
    get :feeds
    get :help
    post :update_credit_card
    post :mark_favicon_complete
    post :update_plan
    post :font
    post :font_increase
    post :font_decrease
    post :entry_width
  end

  constraints subdomain: 'api' do
    namespace :api, path: nil do
      namespace :v1 do
        match '*path', to: 'api#gone', via: :all
      end
    end
  end

  constraints subdomain: 'api' do
    namespace :api, path: nil do
      namespace :v2 do
        resources :feeds, only: [:show] do
          resources :entries, only: [:index, :show], controller: :feeds_entries
        end
        resources :subscriptions,  only: [:index, :show, :create, :destroy, :update]
        post "subscriptions/:id/update", to: 'subscriptions#update'

        resources :taggings,       only: [:index, :show, :create, :destroy]
        resources :entries,        only: [:index, :show]

        resources :unread_entries, only: [:index, :show, :create]
        delete 'unread_entries', to: 'unread_entries#destroy'
        post 'unread_entries/delete', to: 'unread_entries#destroy'

        resources :starred_entries, only: [:index, :show, :create]
        delete 'starred_entries', to: 'starred_entries#destroy'
        post 'starred_entries/delete', to: 'starred_entries#destroy'

        resources :saved_searches,  only: [:index, :show, :create, :destroy, :update]
        post "saved_searches/:id/update", to: 'saved_searches#update'
      end
    end
  end

end

feedbin/app/models/feed.rb
class Feed < ActiveRecord::Base
  has_many :subscriptions
  has_many :entries
  has_many :users, through: :subscriptions
  has_many :unread_entries
  has_many :starred_entries

  has_many :taggings
  has_many :tags, through: :taggings

  attr_accessor :unread_count, :tags

  def tag(names, user, delete_existing = true)
    taggings = []
    if delete_existing
      Tagging.delete_all(user_id: user, feed_id: self.id)
    end
    names.split(",").map do |name|
      name = name.strip
      unless name.blank?
        tag = Tag.where(name: name.strip).first_or_create!
        taggings << self.taggings.where(user: user, tag: tag).first_or_create!
      end
    end
    taggings
  end

  def self.create_from_feedzirra(feed, site_url)
    feed.url = site_url
    feed_record = self.create!(feed: feed)
    ActiveRecord::Base.transaction do
      feed.entries.each do |entry|
        feed_record.entries.create!(entry: entry)
      end
    end
    feed_record
  end

  def feed=(feed)
    self.etag          = feed.etag
    self.last_modified = feed.last_modified
    self.title         = feed.title
    self.feed_url      = feed.feed_url
    self.site_url      = feed.url
  end

  def cache_key
    additions = []
    if unread_count
      additions << "/#{unread_count}"
    end
    super + additions.join('')
  end

  def check
    options = {}
    unless last_modified.blank?
      options[:if_modified_since] = last_modified
    end
    unless etag.blank?
      options[:if_none_match] = etag
    end
    feed_fetcher = FeedFetcher.new(feed_url)
    feed_fetcher.fetch_and_parse(options, feed_url)
  end

  def self.include_user_title
    select('feeds.*, subscriptions.title AS user_title').
      map {|feed|
        if feed.user_title
          feed.title = feed.user_title
        elsif feed.title
          feed.title = feed.title
        else
          feed.title = '(No title)'
        end
        feed
      }.
      sort_by {|feed| feed.title.try(:downcase)}
  end

  def string_id
    self.id.to_s
  end
end

feedbin/app/controllers/settings_controller.rb
class SettingsController < ApplicationController

  before_action :plan_exists, only: [:update_plan]

  def help
    @user = current_user
  end

  def settings
    @user = current_user
  end

  def sharing
    @user = current_user
  end

  def account
    @user = current_user
  end

  def feeds
    @user = current_user
    @subscriptions = @user.subscriptions.select('subscriptions.*, feeds.title AS original_title, feeds.feed_url, feeds.site_url').joins("INNER JOIN feeds ON subscriptions.feed_id = feeds.id AND subscriptions.user_id = #{@user.id}")
    @subscriptions = @subscriptions.map {|subscription|
      if subscription.title
        subscription.title = subscription.title
      elsif subscription.original_title
        subscription.title = subscription.original_title
      else
        subscription.title = '(No title)'
      end
      subscription
    }
    @subscriptions = @subscriptions.sort_by {|subscription| subscription.title.downcase}

    verifier = ActiveSupport::MessageVerifier.new(Feedbin::Application.config.secret_key_base)
    @authentication_token = CGI::escape(verifier.generate(@user.id))
    @web_service_url = "#{ENV['PUSH_URL']}/apple_push_notifications"
  end

  def billing
    @user = current_user
    @next_payment = @user.billing_events.where(event_type: 'invoice.payment_succeeded')
    @next_payment = @next_payment.to_a.sort_by {|next_payment| -next_payment.details.data.object.date }
    if @next_payment.present?
      @next_payment.first.details.data.object.lines.data.each do |event|
        event = event.to_hash
        if event[:type] && event[:type] == 'subscription'
          @next_payment = Time.at(event[:period].end).utc.to_datetime
        end
      end
    end
    @billing_events = @user.billing_events.where(event_type: 'charge.succeeded')
    @billing_events = @billing_events.to_a.sort_by {|billing_event| -billing_event.details.data.object.created }
    if @user.plan.stripe_id == 'free'
      @plans = Plan.where(price_tier: @user.plan.price_tier)
    else
      @plans = Plan.where(price_tier: @user.plan.price_tier).where.not(stripe_id: ['free', 'trial'])
    end
  end

  def import_export
    @user = current_user
    @uploader = Import.new.upload
    @uploader.success_action_redirect = settings_import_export_url

    if params[:key]
      @import = Import.new(key: params[:key], user: @user)

      if @import.save
        redirect_to settings_import_export_url, notice: 'Import has started.'
      else
        @messages = @import.errors.full_messages
        flash[:error] = render_to_string partial: "shared/messages"
        redirect_to settings_import_export_url
      end
    end
  end

  def mark_favicon_complete
    session[:favicon_complete] = true
    render nothing: true
  end

  def update_plan
    plan = Plan.find(params[:plan])
    @user = current_user
    @user.plan = plan
    @user.save
    customer = Stripe::Customer.retrieve(@user.customer_id)
    customer.update_subscription(plan: plan.stripe_id)
    redirect_to settings_billing_path
  end

  def update_credit_card
    @user = current_user
    @user.stripe_token = params[:stripe_token]
    @user.free_ok = (@user.plan.stripe_id == 'free')

    respond_to do |format|
      if @user.save
        format.html { redirect_to settings_billing_url, notice: 'Your credit card has been updated.' }
      else
        format.html { redirect_to settings_billing_url, alert: @user.errors.messages[:base].join(' ') }
      end
    end
  end

  def settings_update
    @user = current_user
    @user.attributes = user_settings_params
    @user.free_ok = (@user.plan.stripe_id == 'free')
    if @user.save
      if params[:redirect_to]
        redirect_to params[:redirect_to], notice: 'Settings updated.'
      else
        redirect_to settings_path, notice: 'Settings updated.'
      end
    else
      redirect_to settings_path, alert: @user.errors.full_messages.join('. ') + '.'
    end
  end

  def view_settings_update
    if params[:tag_visibility]
      session[:tag_visibility] ||= {}
      tag_id = params[:tag].to_s
      if session[:tag_visibility][params[:tag]].blank?
        session[:tag_visibility][tag_id] = true
      else
        session[:tag_visibility][tag_id] = false
      end
    end

    if params[:column_widths]
      session[:column_widths] ||= {}
      session[:column_widths][params[:column]] = params[:width]
    end
    render nothing: true
  end

  def font_increase
    change_font_size('increase')
  end

  def font_decrease
    change_font_size('decrease')
  end

  def font
    @user = current_user
    if Feedbin::Application.config.fonts.has_value?(params[:font])
      @user.font = params[:font]
      @user.save
    end
    render nothing: true
  end

  def entry_width
    @user = current_user
    if @user.entry_width.blank?
      new_width = 'fluid'
    else
      new_width = ''
    end
    @user.entry_width = new_width
    @user.save
    render nothing: true
  end

  private

  def change_font_size(direction)
    @user = current_user

    current_font_size = @user.font_size.try(:to_i) || 5
    if direction == 'increase'
      new_font_size = current_font_size + 1
    else
      new_font_size = current_font_size - 1
    end

    if Feedbin::Application.config.font_sizes[new_font_size] && new_font_size >= 0
      @user.font_size = new_font_size
      @user.save
    end

    render nothing: true
  end

  def plan_exists
    render_404 unless Plan.exists?(params[:plan].to_i)
  end

  def user_settings_params
    params.require(:user).permit(:entry_sort, :starred_feed_enabled, :hide_tagged_feeds, :precache_images, :show_unread_count, :sticky_view_inline, :mark_as_read_confirmation, :apple_push_notification_device_token, :receipt_info)
  end

end

feedbin/app/helpers/settings_helper.rb
module SettingsHelper
end

feedbin/app/views/settings/_sidebar.html.erb
<ul class="nav">
  <li><%= link_to 'Settings', settings_path, class: is_active?('settings', 'settings') %></li>
  <li><%= link_to 'Feeds', settings_feeds_path, class: is_active?('settings', 'feeds') %></li>
  <li><%= link_to 'Sharing', sharing_services_path, class: is_active?('sharing_services', 'index') %></li>
  <li><%= link_to 'Account', settings_account_path, class: is_active?('settings', 'account') %></li>
  <li><%= link_to 'Billing', settings_billing_path, class: is_active?('settings', 'billing') %></li>
  <li><%= link_to 'Import/Export', settings_import_export_path, class: is_active?('settings', 'import_export') %></li>
  <li><%= link_to 'Help', settings_help_path, class: is_active?('settings', 'help') %></li>
</ul>

feedbin/app/views/settings/account.html.erb
<h2>Account</h2>

<h3>Email</h3>

<%= form_for(@user) do |f| %>

  <%= f.email_field :email, placeholder: 'Email' %>

  <br />

  <%= f.submit "Update", class: 'button' %>
<% end %>

<h3>Update Password</h3>

<%= form_for(@user) do |f| %>

  <%= f.password_field :old_password, placeholder: 'Old Password' %>

  <%= f.password_field :password, placeholder: 'New Password' %>

  <br />

  <%= f.submit "Update", class: 'button' %>
<% end %>

<hr />

<h3>Cancel Account</h3>
<p class="muted">Canceling your account will end your subscription immediately. All of your data will be deleted. <strong>You cannot undo this</strong>.</p>
<p><%= link_to "Cancel Account", user_path(@user), data: { confirm: "Are you sure?" }, method: :delete, class: 'button button-danger button-link' %></p>

feedbin/app/views/settings/billing.html.erb
<h3>Update Billing</h3>
<% if ENV['STRIPE_API_KEY'] %>
  <% if @user.plan.stripe_id == 'trial' %>
    <% if @user.days_left <= 0 %>
      <p>Your trial has ended. Subscribe now to continue using Feedbin.</p>
    <% else %>
      <p>Your trial period will end in <%= pluralize(@user.days_left, 'day') %>. Subscribe now to continue using Feedbin uninterrupted.</p>
    <% end %>

    <div data-behavior="stripe_error" class="alert alert-error hide"></div>
    <%= form_for @user, html: { data: { behavior: 'credit_card_form' } } do |f| %>
      <%= f.hidden_field :stripe_token, data: { behavior: 'stripe_token' } %>
      <%= hidden_field_tag :redirect_to, settings_billing_url %>
      <div class="form-wrap">
        <% if @user.stripe_token %>
          <p>Credit card acceptance is pending.</p>
        <% else %>
          <%= render partial: 'shared/credit_card_form' %>
        <% end %>
      </div>

      <div class="plan-options">
        <% Plan.where(price_tier: Feedbin::Application.config.price_tier).where.not(stripe_id: ['free', 'trial']).each do |plan| %>
          <% options = plan.stripe_id =~ /^basic-monthly/ ? {checked: true} : {} %>
          <%= label_tag nil, class: 'radio' do %>
            <%= f.radio_button :plan_id, plan.id, options %>
            <%= number_to_currency(plan.price, precision: 0) %>/<%= plan.name.gsub(/ly$/, '').downcase %>
          <% end %>
        <% end %>
      </div>

      <%= f.submit "Subscribe", class: 'button', tabindex: 3 %>

    <% end %>
  <% else %>
    <% if @user.last_4_digits %>
      <p class="billing-promo">Your current card **** **** **** <%= @user.last_4_digits %></p>
    <% end %>
    <div data-behavior="stripe_error" class="alert alert-error hide"></div>
    <%= form_tag settings_update_credit_card_path, data: { behavior: 'credit_card_form' } do %>
      <%= hidden_field_tag :stripe_token, nil, data: { behavior: 'stripe_token' } %>
      <%= render partial: 'shared/credit_card_form' %>
      <%= submit_tag "Update", class: 'button' %>
    <% end %>

    <h3>Change your Plan</h3>
    <table class="table table-bordered" style="margin-bottom: 0;">
      <tr>
        <th>Plan</th>
        <th>Price</th>
        <th>&nbsp;</th>
      </tr>
      <% @plans.each do |plan| %>
        <tr>
            <td><%= plan.name %></td>
            <td><%= number_to_currency(plan.price) %>/<%= plan.name %></td>
            <td>
              <% if @user.plan.id == plan.id %>
                Your plan
              <% else %>
                <%= form_tag settings_update_plan_path, data: { behavior: 'change_plan' }, class: 'no-margin' do %>
                  <%= hidden_field_tag 'plan', plan.id %>
                  <%= button_tag 'Switch', data: { confirm: 'Are you sure you want to change plans?' }, class: 'button button-link' %>
                <% end %>
              <% end %>
            </td>
        </tr>
      <% end %>
    </table>

    <p><small>Plan changes are pro-rated.</small></p>

    <h3 class="por">
      Payment History
      <% if @next_payment %>
        <p class="inline-subhead"><small>Next payment: <time datetime="<%= @next_payment.to_s(:date) %>"><%= @next_payment.to_s(:date) %></time></small></p>
      <% end %>
    </h3>

    <table class="table table-bordered">
      <tr>
        <th>Date</th>
        <th>Receipt</th>
        <th>Amount</th>
      </tr>
      <% @billing_events.each do |invoice| %>
      <tr>
        <td><%= Time.at(invoice.details.data.object.created).to_s(:date) %></td>
        <td><%= link_to 'Receipt', invoice %></td>
        <td><%= invoice.details.data.object.currency.upcase %> <%= number_to_currency(invoice.details.data.object.amount.to_f / 100) %></td>
      </tr>
      <% end %>
    </table>

    <h3 class="no-margin">Receipt Info</h3>
    <p><small>This will show up on your receipt. Useful for VAT, address etc...</small></p>

    <%= form_for @user, url: settings_update_user_path(@user) do |f| %>
      <%= hidden_field_tag :redirect_to, settings_billing_url %>
      <%= f.text_area :receipt_info, rows: 3 %>
      <p><%= f.submit "Save", class: 'button' %></p>
    <% end %>

  <% end %>
<% else %>
  <p>Billing disabled. <code>STRIPE_API_KEY</code> and <code>STRIPE_PUBLIC_KEY</code> are missing.</p>
<% end %>

feedbin/app/views/settings/feeds.html.erb
<h2>Feeds</h2>

<p class="half-margin">Select: <a href="#" data-behavior="check_all">All</a> / <a href="#" data-behavior="check_none">None</a></p>
<%= form_tag update_multiple_subscriptions_path, method: :patch do %>
  <div class="collection-edit-wrapper">
    <table class="table form-table feed-form">
      <% @subscriptions.each do |subscription| %>
        <%= fields_for "subscriptions[]", subscription do |f| %>
          <tr>
            <td width="15"><%= check_box_tag "subscription_ids[]", subscription.id %></td>
            <td>
              <%= f.text_field :title %>
              <br /><small title="Original title"><%= link_to subscription.site_url, subscription.site_url, target: '_blank' %></small>
              <br /><small class="highlight break-word" title="Feed URL"><%= link_to subscription.feed_url, subscription.feed_url, target: '_blank' %></small>
            </td>
          </tr>
        <% end %>
      <% end %>
    </table>
  </div>
  <div class="collection-edit-controls clearfix">
    <div class="half text-right float-right">
      <%= submit_tag "Save", class: 'button button-primary' %>
    </div>
    <div class="half">
      <%= submit_tag 'Unsubscribe', class: 'button button-danger button-link', name: 'unsubscribe', style: 'margin-top: 11px;' %>
    </div>
  </div>

<% end %>

feedbin/app/views/settings/help.html.erb
<h2>Help</h2>

<p>
  <strong>Email support:</strong>
  <% if ENV['FROM_ADDRESS'] %>
    <a href="mailto:<%= ENV['FROM_ADDRESS'] %>"><%= ENV['FROM_ADDRESS'] %></a>
  <% end %>
</p>
<p>
  <strong>Issue tracker:</strong>
  <% if ENV['SUPPORT_URL'] %>
    <a href="<%= ENV['SUPPORT_URL'] %>">Open a new support request</a>
  <% end %>
</p>
<p><strong>Public homepage:</strong> <a href="/home">feedbin.me/home</a></p>

<hr />

<h3>Keyboard Shortcuts</h3>
<p class="muted">You can bring this up in the app by pressing <span class="key">?</span></p>
<%= render partial: "shared/keyboard_shortcuts" %>

feedbin/app/views/settings/import_export.html.erb
<h2>Import/Export</h2>

<h3>Import</h3>
<% if ENV['AWS_ACCESS_KEY_ID'] %>
  <%= direct_upload_form_for @uploader do |f| %>
    <p><%= f.file_field :upload %></p>
    <p><%= f.submit "Import", class: 'button' %></p>
  <% end %>

  <p><small>You can import OPML or starred.json files. Import is done in the background so you may not see every subscription or starred item right away.</small></p>

  <hr />
<% else %>
  <p>Import disabled. <code>AWS_ACCESS_KEY_ID</code>, <code>AWS_SECRET_ACCESS_KEY</code> and <code>AWS_S3_BUCKET</code> are missing.</p>
<% end %>

<h3>Export</h3>
<p><%= link_to "Download Subscriptions", subscriptions_path(format: :xml) %></p>

feedbin/app/views/settings/settings.html.erb
<h2>Settings</h2>

<%= form_for @user, url: settings_update_user_path(@user) do |f| %>
  <h3>Reading</h3>
  <p>
    <%= label_tag nil do %>
      Sort entries by <%= f.select :entry_sort, options_for_select([['Newest first', 'DESC'], ['Oldest first', 'ASC']], @user.entry_sort || 'DESC') %>
    <% end %>
  </p>

  <p>
    <label class="checkbox">
      <%= f.check_box :precache_images %> Pre-load images
    </label>
    <small>Images for unread entries will be loaded in the background when viewing a feed. Not recommended with limited data/bandwidth.</small>
  </p>

  <p>
    <label class="checkbox">
      <%= f.check_box :sticky_view_inline %> Sticky Readability
    </label>
    <small>Use last Readability setting per feed (this will make loading entries slower).</small>
  </p>

  <p>
    <label class="checkbox">
      <%= f.check_box :mark_as_read_confirmation %> Ask before marking all as read
    </label>
  </p>

  <h3>Tags</h3>

  <p>
    <label class="checkbox">
      <%= f.check_box :hide_tagged_feeds %> Hide tagged feeds
    </label>
    <small>Tagged feeds will only show up in tag drawers</small>
  </p>

  <h3>Extras</h3>

  <p>
    <label class="checkbox">
      <%= f.check_box :show_unread_count %> Show unread count in title
    </label>
  </p>

  <p>
    <label class="checkbox">
      <%= f.check_box :starred_feed_enabled %> Enable starred entry feed
    </label>
    <% if @user.starred_feed_enabled == '1' %>
      <small><%= link_to 'Starred Feed', starred_url(@user.starred_token, format: :xml) %></small>
    <% else %>
      <small>Link shown here when enabled</small>
    <% end %>
  </p>


  <%= f.submit "Save", class: 'button' %>
<% end %>

<hr />

<h3>Subscribe via Email</h3>
<p class="muted">You can subscribe to any website that publishes a feed by sending an email to this secret address. The body of the email should only contain the URL to the website or feed.</p>

<p class="subscribe-email"><a href="mailto:subscribe+<%= @user.inbound_email_token %>@subscribe.feedbin.me">subscribe+<%= @user.inbound_email_token %>@subscribe.feedbin.me</a></p>