feedbin/config/routes.rb
require 'sidekiq/web'

Feedbin::Application.routes.draw do

  root to: 'site#index'

  mount Sidekiq::Web, at: '/sidekiq'
  mount StripeEvent::Engine, at: '/stripe'

  get :health_check, to: proc {|env| [200, {}, ["OK"]] }

  get :home, to: 'site#home'
  get :apps, to: 'site#apps'

  get :manifest, to: 'site#manifest'

  post '/emails' => 'emails#create'

  match '/404', to: 'errors#not_found', via: :all
  get '/starred/:starred_token', to: 'starred#index', as: 'starred'

  get    :signup,         to: 'users#new',           as: 'signup'
  get    :login,          to: 'sessions#new',        as: 'login'
  get    :privacy_policy, to: 'site#privacy_policy', as: 'privacy_policy'
  delete :logout,         to: 'sessions#destroy',    as: 'logout'

  post 'apple_push_notifications/:version/pushPackages/:website_push_id', as: :apple_push_notifications_package, to: 'apple_push_notifications#create', website_push_id: /.*/

  post 'apple_push_notifications/:version/devices/:device_token/registrations/:website_push_id', as: :apple_push_notifications_update, to: 'apple_push_notifications#update', website_push_id: /.*/

  delete 'apple_push_notifications/:version/devices/:device_token/registrations/:website_push_id', as: :apple_push_notifications_delete, to: 'apple_push_notifications#delete', website_push_id: /.*/

  post 'apple_push_notifications/:version/log', as: :apple_push_notifications_log, to: 'apple_push_notifications#log'

  resources :tags,           only: [:index, :show, :update, :destroy]
  resources :billing_events, only: [:show]
  resources :imports
  resources :sessions
  resources :password_resets
  resources :sharing_services, path: 'settings/sharing', only: [:index]
  resources :actions, path: 'settings/actions', only: [:index]
  resources :saved_searches

  resources :subscriptions,  only: [:index, :create, :destroy] do
    collection do
      patch :update_multiple
    end
  end

  resources :users, id: /.*/ do
    member do
      patch :settings_update, controller: :settings
      patch :view_settings_update, controller: :settings
      patch :sharing_services_update, controller: :sharing_services
      patch :actions_update, controller: :actions
    end
  end

  resources :feeds, only: [:index, :edit, :create, :update] do
    resources :entries, only: [:index], controller: :feeds_entries
    collection do
      get :view_unread
      get :view_all
      get :auto_update
    end
  end

  resources :entries, only: [:show, :index] do
    member do
      post :content
      post :unread_entries, to: 'unread_entries#update'
      post :starred_entries, to: 'starred_entries#update'
      post :mark_as_read, to: 'entries#mark_as_read'
      get :push_view
    end
    collection do
      get :starred
      get :unread
      get :preload
      get :search
      post :mark_all_as_read
      post :mark_direction_as_read
    end
  end

  get :settings, to: 'settings#settings'
  namespace :settings do
    get :account
    get :billing
    get :import_export
    get :feeds
    get :help
    post :update_credit_card
    post :mark_favicon_complete
    post :update_plan
    post :font
    post :font_increase
    post :font_decrease
    post :entry_width
  end

  constraints subdomain: 'api' do
    namespace :api, path: nil do
      namespace :v1 do
        match '*path', to: 'api#gone', via: :all
      end
    end
  end

  constraints subdomain: 'api' do
    namespace :api, path: nil do
      namespace :v2 do
        resources :feeds, only: [:show] do
          resources :entries, only: [:index, :show], controller: :feeds_entries
        end
        resources :subscriptions,  only: [:index, :show, :create, :destroy, :update]
        post "subscriptions/:id/update", to: 'subscriptions#update'

        resources :taggings,       only: [:index, :show, :create, :destroy]
        resources :entries,        only: [:index, :show]

        resources :unread_entries, only: [:index, :show, :create]
        delete 'unread_entries', to: 'unread_entries#destroy'
        post 'unread_entries/delete', to: 'unread_entries#destroy'

        resources :starred_entries, only: [:index, :show, :create]
        delete 'starred_entries', to: 'starred_entries#destroy'
        post 'starred_entries/delete', to: 'starred_entries#destroy'

        resources :saved_searches,  only: [:index, :show, :create, :destroy, :update]
        post "saved_searches/:id/update", to: 'saved_searches#update'
      end
    end
  end

end

feedbin/app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessor :unread_count, :user_feeds

  has_many :taggings
  has_many :feeds, through: :taggings
end

feedbin/app/controllers/tags_controller.rb
class TagsController < ApplicationController

  before_action :user_owns_tag, only: [:show]

  def index
    @user = current_user
    @tags = @user.feed_tags.pluck(:name)

    @tags = @tags.find_all { |tag| tag.downcase.include?(params[:query].downcase) }.first(3)
    respond_to do |format|
      format.json { render json: { suggestions: @tags.map {|tag| { value: tag, data: tag } } }.to_json }
    end
  end

  def show
    @user = current_user
    update_selected_feed!("tag", params[:id])

    @tag = Tag.find(params[:id])
    @feed_ids = Tagging.where(tag_id: @tag, user_id: @user).pluck(:feed_id)

    feeds_response

    @append = !params[:page].nil?

    @type = 'tag'
    @data = params[:id]

    @collection_title = @tag.name
    @collection_favicon = 'favicon-tag'

    respond_to do |format|
      format.js { render partial: 'shared/entries' }
    end
  end

  def update

    @user = current_user
    tag_name = params[:tag][:name].chomp.gsub(',', '')

    tag = Tag.find(params[:id])
    @taggings = Tagging.where(tag_id: tag, user_id: @user)
    @feed_ids = @taggings.pluck(:feed_id)

    @new_tag = nil
    if !tag_name.empty?
      ActiveRecord::Base.transaction do
        @new_tag = Tag.where(name: tag_name).first_or_create
        @taggings.update_all(tag_id: @new_tag.id)
      end
      update_selected_feed!("tag", @new_tag.try(:id))

      session[:tag_visibility] ||= {}
      session[:tag_visibility][@new_tag.id.to_s] = session[:tag_visibility][tag.id.to_s] ? session[:tag_visibility][tag.id.to_s] : false
    else
      # Tag is empty, delete taggings
      @taggings.destroy_all
    end

    get_feeds_list
    respond_to do |format|
      format.js
    end

  end

  def destroy
    @user = current_user
    tag = Tag.find(params[:id])
    Tagging.where(tag_id: tag, user_id: @user).destroy_all

    get_feeds_list

    respond_to do |format|
      format.js
    end

  end

  private

  def user_owns_tag
    @user = current_user
    tags = Tagging.where(user_id: @user, tag_id: params[:id].to_i)
    unless tags.any?
      render_404
    end
  end

end

feedbin/app/helpers/tags_helper.rb
module TagsHelper
  def drawer_visible?(tag_id)
    session[:tag_visibility] ||= {}
    session[:tag_visibility][tag_id.to_s] || false
  end
end

feedbin/app/views/tags/_tag.html.erb
<% hide_drawer = (session[:view_mode] == 'view_unread' && tag.unread_count == 0 && !tag.user_feeds.any?) ? true : false %>
<li data-tag-id="<%= tag.id %>" data-feed-id="tag-<%= tag.id %>" class="<%= selected("tag_#{tag.id}") %>">
  <%= link_to tag_path(tag.id), remote: true, class: 'feed-link tag-link', data: { behavior: 'selectable reset_entry_position show_entries open_item feed_link', mark_read: {type: 'tag', data: tag.id, message: "Mark #{tag.name} as read?"}.to_json } do %>
    <span class="favicon-wrap">
      <span class="favicon favicon-tag"></span>
    </span>
    <%= content_tag :span, tag.unread_count, class: 'count' + hide_count(tag.unread_count) %>
    <% unless hide_drawer %>
      <%= render partial: 'tags/tag_visibility', locals: {user: @user, tag: tag} %>
    <% end %>
    <%= tag.name %>
  <% end %>
  <div class="drawer <%= hide_drawer ? ' hide' : '' %>" data-hidden="<%= drawer_visible?(tag.id) ? 'false' : 'true' %>" style="<%= drawer_visible?(tag.id) ? '' : 'height: 0;' %>">
    <ul>
      <%= render tag.user_feeds %>
    </ul>
    <i class="drawer-arrow"></i>
  </div>
</li>

feedbin/app/views/tags/_tag_visibility.html.erb
<%= form_for @user, url: view_settings_update_user_path(@user), remote: 'true', html: { class: 'toggle-drawer' } do |f| %>
  <%= hidden_field_tag 'tag_visibility', 'tag_visibility' %>
  <%= hidden_field_tag 'tag', tag.id %>
  <% if drawer_visible?(tag.id) %>
    <%= f.button "hide", class: 'feed-action-button', data: { behavior: 'toggle_drawer' } %>
  <% else %>
    <%= f.button "show", class: 'feed-action-button', data: { behavior: 'toggle_drawer' } %>
  <% end %>
<% end %>

feedbin/app/views/tags/destroy.js.erb
feedbin.updateFeeds('<%= j render partial: 'feeds/feeds', locals: {collections: @collections, saved_searches: @saved_searches, tags: @tags, feeds: @feeds} %>');
feedbin.updateEntries('');
feedbin.updateEntryContent('');
feedbin.hideTagsForm();
$('.app').addClass('nothing-selected').removeClass('feed-selected entry-selected')
$('[data-behavior~=show_tags_form]').replaceWith('<%= j render partial: "shared/buttons/tag", locals: {feed: nil, tags: nil, tag: nil} %>');
$('[data-behavior~=unsubscribe]').replaceWith('<%= j render partial: "shared/buttons/destroy_tag", locals: {tag: nil} %>');
feedbin.disableMarkRead()

feedbin/app/views/tags/update.js.erb
feedbin.updateFeeds('<%= j render partial: 'feeds/feeds', locals: {collections: @collections, saved_searches: @saved_searches, tags: @tags, feeds: @feeds} %>');
$('[data-behavior~=feeds_target] [data-tag-id~=<%= @new_tag.id %>] .tag-link').click()
feedbin.hideTagsForm();
$('[data-behavior~=show_tags_form]').replaceWith('<%= j render partial: "shared/buttons/tag", locals: {feed: nil, tags: nil, tag: @new_tag} %>');
$('[data-behavior~=unsubscribe]').replaceWith('<%= j render partial: "shared/buttons/destroy_tag", locals: {tag: @new_tag} %>');